create extension if not exists pgcrypto;
create table if not exists public.products (id uuid primary key default gen_random_uuid(),name text not null,description text,cooking text,image_url text,status text not null default 'available' check (status in ('available','sold_out','hidden')),featured boolean not null default false,sort_order integer not null default 100,created_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(),customer_name text not null,phone text not null,line_id text,fulfillment text not null,processing text not null,note text,status text not null default 'new' check (status in ('new','contacted','confirmed','paid','shipped','completed','cancelled')),created_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,quantity integer not null default 1 check (quantity>0),created_at timestamptz not null default now());
alter table public.products enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;
drop policy if exists "public read visible products" on public.products;create policy "public read visible products" on public.products for select to anon, authenticated using (status <> 'hidden');
drop policy if exists "public create orders" on public.orders;create policy "public create orders" on public.orders for insert to anon, authenticated with check (true);
drop policy if exists "public create order items" on public.order_items;create policy "public create order items" on public.order_items for insert to anon, authenticated with check (true);
insert into public.products(name,description,cooking,status,featured,sort_order) select * from (values ('馬頭','肉質細嫩鮮甜，帶有自然海味。','清蒸、煮湯、立鱗燒','available',true,1),('赤棕','肉質細緻，適合家庭日常料理。','清蒸、乾煎','available',false,2),('黃雞魚','口感細緻有彈性，味道清甜少腥。','清蒸、乾煎、煮湯','available',false,3),('秋姑','今日到貨，已被客人預訂完畢。','煮湯、乾煎','sold_out',false,4),('赤鼻仔','今日到貨，已被客人預訂完畢。','煮湯、清蒸','sold_out',false,5)) as data(name,description,cooking,status,featured,sort_order) where not exists(select 1 from public.products);
